### ISSUE TITLE
Condensing Code

### ISSUE THREAD

**Issue by sunain-s** [sunain-s/Pong#1]
At the moment i have multiple files in order to have different score modes. I'm fully aware that i could do this with a variable and 1 file for splayer and mplayer. However when I try to import a variable i assigned in mode_s.py or mode_m.py to the game files it has error - either runs and does not end when reaching the required score, or it crashes and says that the variable does not exist in module mode_s. Any idea how to fix this as it will condense the code significantly.

Here's the link to the full repo:
https://github.com/Asianguy123/Pong

**Comment by iamAbhishekkumar** [comment]
Could you reproduce the error you are getting? Or elaborate on defining what you are getting the error.

**Comment by sunain-s** [comment]
> Could you reproduce the error you are getting? Or elaborate on defining what you are getting the error.

Thanks for your response. I have since fixed the error I was getting and found out that it was due to my way of defining the variable I wanted to call within a function.
